In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
pd.read_csv('./output/selection_coefficients/YAP1_fig3.csv.gz')

     site amino_acid    rep_1     rep_2    joint
0       2          A  0.06310  0.086900  0.06450
1       2          R  0.05210  0.051000  0.08840
2       2          N -0.05600 -0.092200 -0.08870
3       2          D -0.18000 -0.184000 -0.19500
4       2          C  0.00273  0.003270  0.00414
..    ...        ...      ...       ...      ...
709    35          T  0.00378  0.002820  0.00670
710    35          W  0.00000  0.000000  0.00000
711    35          Y -0.01350 -0.011200 -0.02300
712    35          V  0.00244  0.000896  0.00347
713    35          * -0.00209 -0.001510 -0.00345

[714 rows x 5 columns]

In [3]:
pd.read_csv('./output/selection_coefficients/YAP1.csv.gz')

     site amino_acid  WT_indicator    rep_1    rep_2    joint
0       1          A         False  0.04870  0.07190  0.04700
1       1          R         False  0.06140  0.06000  0.09880
2       1          N         False -0.06850 -0.09980 -0.10100
3       1          D          True -0.19200 -0.19400 -0.20700
4       1          C         False  0.00120  0.00356  0.00217
..    ...        ...           ...      ...      ...      ...
709    34          T         False  0.00401 -0.00266  0.00185
710    34          W         False -0.00669 -0.00508 -0.01130
711    34          Y         False -0.01260 -0.01250 -0.02130
712    34          V         False -0.00441 -0.01010 -0.01330
713    34          *         False -0.00568 -0.00561 -0.01090

[714 rows x 6 columns]

In [24]:
AA = ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', '*']
SELECTION_FILE = './output/selection_coefficients/YAP1.csv.gz'
Amino_acid_dict = {'Ala': 'A',
                   'Arg': 'R',
                   'Asn': 'N',
                   'Asp': 'D',
                   'Cys': 'C',
                   'Gln': 'Q',
                   'Glu': 'E',
                   'Gly': 'G',
                   'His': 'H',
                   'Ile': 'I',
                   'Leu': 'L',
                   'Lys': 'K',
                   'Met': 'M',
                   'Phe': 'F',
                   'Pro': 'P',
                   'Ser': 'S',
                   'Thr': 'T',
                   'Trp': 'W',
                   'Tyr': 'Y',
                   'Val': 'V',
                   'Ter': '*'
                  }
df_enrich   = pd.read_csv('./data/prefs/YAP1_prefs.csv.gz')
df_enrich['hgvs_pro'].astype(str)
df_enrich   = df_enrich[~df_enrich['hgvs_pro'].str.contains('\[')]
df_enrich   = df_enrich[ df_enrich['hgvs_pro'].str.contains('p.')]
mutant_list = df_enrich['hgvs_pro'].tolist()
pref_list   = df_enrich['score_101208'].tolist()
AA_dict     = {}
for aa in AA:
    if aa != '*':
        AA_dict[aa] = [0] * 34
site_lll = set()
for i in range(len(mutant_list)):
    if mutant_list[i][-1] != '?':
        mutants = mutant_list[i][-3:]
        site_lll.add(int(mutant_list[i][5: -3]))
        short_AA = Amino_acid_dict[mutants]
        if short_AA != '*':
            if mutant_list[i][5:-3] != '':
                site = int(mutant_list[i][5: -3]) - 1
            AA_dict[short_AA][site] = pref_list[i]

df_AA = pd.DataFrame(columns = ['site', 'amino_acid', 'pref'])
site_list = []
amino_acid_list = []
pref_list = []
for aa, pref in AA_dict.items():
    for i in range(len(pref)):
        site_list.append(i + 2)
        pref_list.append(pref[i])
        amino_acid_list.append(aa)
df_AA['site'] = site_list
df_AA['amino_acid'] = amino_acid_list
df_AA['pref'] = pref_list
data2 = pd.pivot_table(df_AA, values = 'pref', index = ['site'], columns = ['amino_acid']).reset_index()
data2['site'] = [str(i) + '_Pref' for i in data2['site'].tolist()]

data = pd.read_csv(SELECTION_FILE)
site_list = data['site'].unique().tolist()
rep_list = data.columns[2:]

sites_per_line = 35
exp_scale = 10
plt.figure()
data1 = data[['site', 'amino_acid', 'joint']]

# data1 = pd.pivot_table(data1, values = 1, index=['site'], columns = ['amino_acid']).reset_index()
# data1 = data1.drop(['*'], axis = 1)
# data1['site'] = [str(i) + '_MPL' for i in data1['site'].tolist()]


# df_all  = data1[0: 0].copy()
# df_zero = data1[0: 1].copy()
# for col in df_zero.columns:
#     df_zero[col].values[:] = 0
# # selected_rows = [10, 16, 27, 
# #                  4,  13, 28,
# #                  29, 30, 20]
# selected_rows = [9,  15, 26, 
#                  3,  12, 27,
#                  28, 29, 19]
# k = 10 * len(selected_rows)
# m = 0
# for i in selected_rows:
#     #MPL
#     if m%3 == 0:
#         # df_all = df_all.concat(df_zero)
#         df_all = pd.concat([df_all, df_zero])
#     m += 1
#     # df_all    = df_all.concat(df_zero)
#     df_all = pd.concat([df_all, df_zero])
#     df_temp   = data1[data1['site'] == str(i) + '_MPL'].copy()
#     temp_pure = df_temp[df_temp.columns[1:]]

#     temp_pure = np.exp(MPL_scale * temp_pure)
#     temp_pure.replace(1, 0, inplace = True)
#     temp_pure = temp_pure.div(temp_pure.sum(axis = 1), axis = 0)
#     # df_all = df_all.concat(temp_pure)
#     df_all = pd.concat([df_all, temp_pure])

#     #PREF
#     df_temp   = data2[data2['site'] == str(i) + '_Pref'].copy()
#     temp_pure = df_temp[df_temp.columns[1:]]
#     temp_pure = np.exp(PREF_scale * temp_pure)
#     temp_pure.replace(1, 0, inplace = True)
#     temp_pure = temp_pure.div(temp_pure.sum(axis = 1), axis = 0)
#     # df_all = df_all.concat(temp_pure)
#     df_all = pd.concat([df_all, temp_pure])

# df_all['plot_site'] = [i for i in range(10)] + [i for i in range(10)] + [i for i in range(10)]
# plot_index = df_all['site']
# df_all = df_all.drop(['site'], axis = 1)

# df_all.set_index('plot_site', inplace = True)
# total_line_num = len(df_all.columns)
# sites_per_line = int(df_all.shape[0]/3)
# num_line = int(total_line_num/sites_per_line) + 1
data1.sort_values('joint')['joint'].tolist()

[-0.451,
 -0.407,
 -0.379,
 -0.369,
 -0.354,
 -0.332,
 -0.331,
 -0.32,
 -0.311,
 -0.288,
 -0.282,
 -0.278,
 -0.271,
 -0.269,
 -0.244,
 -0.239,
 -0.23,
 -0.227,
 -0.216,
 -0.216,
 -0.21,
 -0.207,
 -0.2,
 -0.185,
 -0.181,
 -0.18,
 -0.179,
 -0.178,
 -0.176,
 -0.176,
 -0.176,
 -0.172,
 -0.168,
 -0.165,
 -0.163,
 -0.161,
 -0.158,
 -0.158,
 -0.151,
 -0.148,
 -0.147,
 -0.146,
 -0.144,
 -0.136,
 -0.131,
 -0.129,
 -0.125,
 -0.124,
 -0.124,
 -0.122,
 -0.119,
 -0.117,
 -0.115,
 -0.114,
 -0.111,
 -0.109,
 -0.102,
 -0.102,
 -0.102,
 -0.102,
 -0.101,
 -0.0958,
 -0.0934,
 -0.093,
 -0.0929,
 -0.0924,
 -0.0909,
 -0.0906,
 -0.0896,
 -0.0879,
 -0.0845,
 -0.0844,
 -0.0835,
 -0.0801,
 -0.0799,
 -0.0792,
 -0.079,
 -0.0786,
 -0.0781,
 -0.0776,
 -0.0771,
 -0.0766,
 -0.076,
 -0.0759,
 -0.0752,
 -0.0751,
 -0.0747,
 -0.0742,
 -0.0737,
 -0.0693,
 -0.0686,
 -0.066,
 -0.0629,
 -0.0625,
 -0.0621,
 -0.0616,
 -0.0601,
 -0.0582,
 -0.0551,
 -0.0544,
 -0.054,
 -0.0518,
 -0.0517,
 -0.0515,
 -0.0512,
 -0.0504,
 -0.0502,
 -0.0499,
 -0.0487,
 -0.0475,
 -0.047,
 -0.0465,
 -0.0457,
 -0.0433,
 -0.0422,
 -0.0413,
 -0.04,
 -0.0391,
 -0.0383,
 -0.0367,
 -0.0356,
 -0.0353,
 -0.0352,
 -0.0351,
 -0.035,
 -0.0343,
 -0.0339,
 -0.0324,
 -0.0323,
 -0.0317,
 -0.0317,
 -0.0303,
 -0.03,
 -0.0297,
 -0.0293,
 -0.0286,
 -0.0276,
 -0.0273,
 -0.0272,
 -0.0271,
 -0.0267,
 -0.0264,
 -0.026,
 -0.0258,
 -0.0258,
 -0.0256,
 -0.0251,
 -0.0251,
 -0.0248,
 -0.0247,
 -0.0245,
 -0.0244,
 -0.0242,
 -0.0242,
 -0.0235,
 -0.0232,
 -0.023,
 -0.0229,
 -0.0226,
 -0.0224,
 -0.0222,
 -0.0221,
 -0.022,
 -0.0216,
 -0.0214,
 -0.0214,
 -0.0213,
 -0.021,
 -0.0209,
 -0.0208,
 -0.0208,
 -0.0207,
 -0.0207,
 -0.0206,
 -0.0206,
 -0.0205,
 -0.0202,
 -0.0201,
 -0.0198,
 -0.0198,
 -0.0197,
 -0.0195,
 -0.0194,
 -0.0193,
 -0.0188,
 -0.0185,
 -0.0184,
 -0.0182,
 -0.0182,
 -0.0179,
 -0.0178,
 -0.0176,
 -0.0174,
 -0.017,
 -0.0168,
 -0.0168,
 -0.0166,
 -0.0164,
 -0.0162,
 -0.0159,
 -0.0159,
 -0.0158,
 -0.0158,
 -0.0156,
 -0.0156,
 -0.0155,
 -0.015,
 -0.0149,
 -0.0148,
 -0.0146,
 -0.0146,
 -0.0146,
 -0.0145,
 -0.0145,
 -0.0145,
 -0.0144,
 -0.0143,
 -0.0142,
 -0.0141,
 -0.0141,
 -0.0141,
 -0.014,
 -0.0139,
 -0.0136,
 -0.0134,
 -0.0134,
 -0.0133,
 -0.0132,
 -0.013,
 -0.013,
 -0.0129,
 -0.0129,
 -0.0124,
 -0.0123,
 -0.0123,
 -0.0122,
 -0.0121,
 -0.012,
 -0.0119,
 -0.0118,
 -0.0118,
 -0.0117,
 -0.0117,
 -0.0116,
 -0.0115,
 -0.0113,
 -0.0112,
 -0.011,
 -0.011,
 -0.0109,
 -0.0109,
 -0.0107,
 -0.0106,
 -0.0105,
 -0.0105,
 -0.0105,
 -0.0102,
 -0.00993,
 -0.0099,
 -0.00978,
 -0.00962,
 -0.00957,
 -0.00937,
 -0.00919,
 -0.00885,
 -0.00877,
 -0.00873,
 -0.00841,
 -0.00797,
 -0.00797,
 -0.00793,
 -0.00763,
 -0.00755,
 -0.00747,
 -0.00746,
 -0.00705,
 -0.00698,
 -0.00684,
 -0.00667,
 -0.00645,
 -0.0063,
 -0.00626,
 -0.00615,
 -0.00596,
 -0.00593,
 -0.00587,
 -0.00582,
 -0.00574,
 -0.00567,
 -0.00534,
 -0.00511,
 -0.00499,
 -0.00484,
 -0.00471,
 -0.00434,
 -0.00433,
 -0.00418,
 -0.00412,
 -0.00395,
 -0.00394,
 -0.00371,
 -0.00364,
 -0.0034,
 -0.0033,
 -0.00322,
 -0.0032,
 -0.00319,
 -0.0028,
 -0.0027,
 -0.00262,
 -0.00256,
 -0.00235,
 -0.00214,
 -0.00208,
 -0.00189,
 -0.00174,
 -0.00153,
 -0.00146,
 -0.00135,
 -0.00106,
 -0.00104,
 -0.000927,
 -0.000878,
 -0.000858,
 -0.000795,
 -0.000586,
 -0.000515,
 -0.000491,
 -0.000386,
 -0.000247,
 -8.29e-05,
 -6.61e-05,
 -1.96e-05,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.94e-05,
 0.000115,
 0.000501,
 0.000649,
 0.000707,
 0.000797,
 0.00081,
 0.0011,
 0.00115,
 0.00144,
 0.00185,
 0.002,
 0.00217,
 0.00225,
 0.00226,
 0.00288,
 0.0029,
 0.00301,
 0.00325,
 0.00337,
 0.00339,
 0.00428,
 0.00435,
 0.00446,
 0.00501,
 0.0056,
 0.00565,
 0.0063,
 0.00639,
 0.00646,
 0.00656,
 0.00659,
 0.00722,
 0.00725,
 0.00755,
 0.00759,
 0.00776,
 0.00795,
 0.00807,
 0.00837,
 0.00857,
 0.00859,
 0.00891,
 0.00939,
 0.00945,
 0.00948,
 0.00952,
 0.0104,
 0.0109,
 0.0113,
 0.0117,
 0.0118,
 0.0121,
 0.0129,
 0.0133,
 0.0134,
 0.0134,
 0.0137,
 0.0141,
 0.0142,
 0.0147,
 0.0147,
 0.0148,
 0.0151,
 0.0151,
 0.0154,
 0.0155,
 0.0159,
 0.0163,
 0.0164,
 0.0166,
 0.0169,
 0.017,
 0.0181,
 0.0185,
 0.0186,
 0.019,
 0.0192,
 0.0193,
 0.0194,
 0.0206,
 0.0212,
 0.0224,
 0.0239,
 0.024,
 0.0241,
 0.0244,
 0.0252,
 0.0253,
 0.0254,
 0.0255,
 0.0263,
 0.0264,
 0.0266,
 0.0268,
 0.0271,
 0.0274,
 0.0285,
 0.0288,
 0.0295,
 0.0296,
 0.0308,
 0.0311,
 0.0322,
 0.0328,
 0.0332,
 0.0337,
 0.0349,
 0.0358,
 0.0382,
 0.0385,
 0.0385,
 0.0385,
 0.0387,
 0.0388,
 0.0391,
 0.0401,
 0.0414,
 0.0418,
 0.0421,
 0.0428,
 0.044,
 0.0445,
 0.0461,
 0.0461,
 0.047,
 0.0477,
 0.0478,
 0.048,
 0.0498,
 0.0501,
 0.0503,
 0.0507,
 0.0522,
 0.0528,
 0.0549,
 0.0556,
 0.0581,
 0.0589,
 0.0591,
 0.0597,
 0.0612,
 0.063,
 0.0631,
 0.0632,
 0.0635,
 0.0677,
 0.0698,
 0.07,
 0.0704,
 0.0734,
 0.0739,
 0.0744,
 0.075,
 0.0752,
 0.0754,
 0.0767,
 0.0774,
 0.0813,
 0.0824,
 0.0859,
 0.0898,
 0.0898,
 0.0922,
 0.0945,
 0.0988,
 0.107,
 0.107,
 0.107,
 0.108,
 0.12,
 0.123,
 0.123,
 0.127,
 0.129,
 0.13,
 0.132,
 0.133,
 0.134,
 0.135,
 0.135,
 0.136,
 0.136,
 0.136,
 0.138,
 0.14,
 0.146,
 0.148,
 0.15,
 0.152,
 0.159,
 0.174,
 0.177,
 0.181,
 0.187,
 0.196,
 0.2,
 0.209,
 0.226,
 0.235,
 0.242,
 0.244,
 0.249,
 0.259,
 0.27,
 0.273,
 0.284,
 0.285,
 0.291,
 0.308,
 0.314,
 0.315,
 0.325,
 0.354,
 0.36,
 0.378,
 0.381,
 0.398,
 0.399,
 0.405,
 0.442,
 0.453,
 0.477,
 0.587,
 0.631]

In [17]:
data

     site amino_acid  WT_indicator    rep_1    rep_2    joint
0       1          A         False  0.04870  0.07190  0.04700
1       1          R         False  0.06140  0.06000  0.09880
2       1          N         False -0.06850 -0.09980 -0.10100
3       1          D          True -0.19200 -0.19400 -0.20700
4       1          C         False  0.00120  0.00356  0.00217
..    ...        ...           ...      ...      ...      ...
709    34          T         False  0.00401 -0.00266  0.00185
710    34          W         False -0.00669 -0.00508 -0.01130
711    34          Y         False -0.01260 -0.01250 -0.02130
712    34          V         False -0.00441 -0.01010 -0.01330
713    34          *         False -0.00568 -0.00561 -0.01090

[714 rows x 6 columns]

In [16]:
df_enrich   = pd.read_csv('./output/merged_preference/YAP1.csv.gz')
df_enrich

     site amino_acid     rep_1     rep_2   average
0       1          R  1.687343  1.531212  1.609277
1       1          Y  0.113136  0.185625  0.149380
2       1          V  1.217566  1.208679  1.213123
3       1          G  0.805947  0.801221  0.803584
4       1          K  1.266313  1.207294  1.236803
..    ...        ...       ...       ...       ...
531    34          N -1.750388 -1.714677 -1.732532
532    34          C -1.863808 -1.842647 -1.853228
533    34          D -1.807598 -1.761197 -1.784397
534    34          L -2.056586 -2.148418 -2.102502
535    34          Q -1.618013 -2.077568 -1.847791

[536 rows x 5 columns]

In [18]:
df_AA = pd.read_csv('./output/merged_preference/YAP1.csv.gz')[['site', 'amino_acid', 'average']]
data2 = pd.pivot_table(df_AA, values = 'average', index = ['site'], columns = ['amino_acid']).reset_index()
data2['site'] = [str(i) + '_Pref' for i in data2['site'].tolist()]

data = pd.read_csv(SELECTION_FILE)
site_list = data['site'].unique().tolist()
rep_list = data.columns[2:]

sites_per_line = 35
exp_scale = 10
plt.figure()
data1 = data[['site', 'amino_acid', 'joint']].copy()

data1 = pd.pivot_table(data1, values = 'joint', index=['site'], columns = ['amino_acid']).reset_index()
data1 = data1.drop(['*'], axis = 1)
data1['site'] = [str(i) + '_MPL' for i in data1['site'].tolist()]

In [31]:
MPL_scale  = 8
PREF_scale = 2

df_AA = pd.read_csv('./output/merged_preference/YAP1.csv.gz')[['site', 'amino_acid', 'average']]
data2 = pd.pivot_table(df_AA, values = 'average', index = ['site'], columns = ['amino_acid']).reset_index()
data2['site'] = [str(i) + '_Pref' for i in data2['site'].tolist()]
data2 = data2.fillna(0)

data = pd.read_csv(SELECTION_FILE)
site_list = data['site'].unique().tolist()
rep_list = data.columns[2:]

sites_per_line = 35
exp_scale = 10
plt.figure()
data1 = data[['site', 'amino_acid', 'joint']].copy()

data1 = pd.pivot_table(data1, values = 'joint', index=['site'], columns = ['amino_acid']).reset_index()
data1 = data1.drop(['*'], axis = 1)
data1['site'] = [str(i) + '_MPL' for i in data1['site'].tolist()]


df_all  = data1[0: 0].copy()
df_zero = data1[0: 1].copy()
for col in df_zero.columns:
    df_zero[col].values[:] = 0
# selected_rows = [10, 16, 27, 
#                  4,  13, 28,
#                  29, 30, 20]
selected_rows = [9,  15, 26, 
                 3,  12, 27,
                 28, 29, 19]
k = 10 * len(selected_rows)
m = 0
for i in selected_rows:
    #MPL
    if m%3 == 0:
        # df_all = df_all.concat(df_zero)
        df_all = pd.concat([df_all, df_zero])
    m += 1
    # df_all    = df_all.concat(df_zero)
    df_all = pd.concat([df_all, df_zero])
    df_temp   = data1[data1['site'] == str(i) + '_MPL'].copy()
    temp_pure = df_temp[df_temp.columns[1:]]

    temp_pure = np.exp(MPL_scale * temp_pure)
    temp_pure.replace(1, 0, inplace = True)
    temp_pure = temp_pure.div(temp_pure.sum(axis = 1), axis = 0)
    # df_all = df_all.concat(temp_pure)
    df_all = pd.concat([df_all, temp_pure])

    #PREF
    df_temp   = data2[data2['site'] == str(i) + '_Pref'].copy()
    temp_pure = df_temp[df_temp.columns[1:]]
    temp_pure = np.exp(PREF_scale * temp_pure)
    temp_pure.replace(1, 0, inplace = True)
    temp_pure = temp_pure.div(temp_pure.sum(axis = 1), axis = 0)
    # df_all = df_all.concat(temp_pure)
    df_all = pd.concat([df_all, temp_pure])

df_all['plot_site'] = [i for i in range(10)] + [i for i in range(10)] + [i for i in range(10)]
plot_index = df_all['site']
df_all = df_all.drop(['site'], axis = 1)

df_all.set_index('plot_site', inplace = True)

total_line_num = len(df_all.columns)
sites_per_line = int(df_all.shape[0]/3)
num_line = int(total_line_num/sites_per_line) + 1

In [34]:
df_all.info()
df_all

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 0 to 9
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       30 non-null     float64
 1   C       30 non-null     float64
 2   D       30 non-null     float64
 3   E       30 non-null     float64
 4   F       30 non-null     float64
 5   G       30 non-null     float64
 6   H       30 non-null     float64
 7   I       30 non-null     float64
 8   K       30 non-null     float64
 9   L       30 non-null     float64
 10  M       30 non-null     float64
 11  N       30 non-null     float64
 12  P       30 non-null     float64
 13  Q       30 non-null     float64
 14  R       30 non-null     float64
 15  S       30 non-null     float64
 16  T       30 non-null     float64
 17  V       30 non-null     float64
 18  W       30 non-null     float64
 19  Y       30 non-null     float64
 20  *       9 non-null      float64
dtypes: float64(21)
memory usage: 5.2 KB

amino_acid,A,C,D,E,F,G,H,I,K,L,...,N,P,Q,R,S,T,V,W,Y,*
plot_site,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,0.089458,0.000000,0.062413,0.027248,0.000000,0.666317,0.013583,0.012087,0.002734,0.009440,...,0.013565,0.012651,0.030089,0.013126,0.017789,0.017132,0.001219,0.000000,0.011149,NaN
3,0.110772,0.000000,0.096312,0.000000,0.000000,0.626607,0.002385,0.001047,0.003722,0.000421,...,0.009499,0.000414,0.049391,0.001171,0.053529,0.040863,0.001458,0.000000,0.001885,0.000524
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
5,0.083692,0.006685,0.042334,0.000000,0.077753,0.050357,0.041808,0.043625,0.000000,0.044609,...,0.039628,0.003254,0.000000,0.048810,0.060096,0.073695,0.044731,0.047160,0.291763,NaN
6,0.079990,0.007315,0.027762,0.000000,0.084626,0.101482,0.033314,0.040181,0.000000,0.030268,...,0.005723,0.002134,0.000000,0.122963,0.000000,0.052716,0.054980,0.098949,0.256289,0.001307
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
8,0.003233,0.000000,0.002672,0.000637,0.000000,0.003106,0.005250,0.000000,0.392499,0.000530,...,0.002368,0.000376,0.012788,0.558098,0.002916,0.002970,0.002939,0.002942,0.003189,NaN
9,0.000636,0.000000,0.000412,0.001380,0.000000,0.000645,0.010390,0.000000,0.393042,0.000918,...,0.000120,0.000458,0.000000,0.585019,0.000677,0.000293,0.000299,0.000356,0.002824,0.000129
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,0.081282,0.000000,0.000000,0.070893,0.000000,0.106690,0.000000,0.079864,0.093049,0.036289,...,0.000000,0.043273,0.066288,0.186332,0.118289,0.060312,0.057439,0.000000,0.000000,NaN
3,0.064008,0.000000,0.000000,0.035908,0.000000,0.169002,0.159460,0.054728,0.126790,0.033806,...,0.000000,0.000000,0.051071,0.139046,0.101291,0.058580,0.005853,0.000000,0.000000,0.000455
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
5,0.049328,0.000000,0.039306,0.067504,0.000000,0.050612,0.068757,0.030771,0.123196,0.073772,...,0.035737,0.041703,0.076232,0.096291,0.059584,0.053228,0.041937,0.000000,0.044731,NaN
6,0.026623,0.000000,0.024219,0.085736,0.000000,0.000000,0.166672,0.038574,0.000000,0.137552,...,0.049465,0.002531,0.079850,0.102409,0.086198,0.073422,0.021268,0.000000,0.034773,0.001606
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
8,0.016442,0.048843,0.063043,0.000000,0.067641,0.034877,0.041306,0.039608,0.053894,0.051698,...,0.027413,0.003139,0.045142,0.142568,0.072343,0.129518,0.045881,0.000000,0.052532,NaN
9,0.021689,0.063053,0.003068,0.000000,0.160087,0.000720,0.012486,0.035620,0.042230,0.093983,...,0.036060,0.001341,0.000000,0.252273,0.069076,0.000000,0.044865,0.000000,0.102515,0.000000
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,0.006781,0.028370,0.025223,0.000000,0.024664,0.030342,0.038603,0.006673,0.022281,0.023678,...,0.021510,0.014781,0.000000,0.024079,0.082281,0.570287,0.024684,0.000000,0.031354,NaN
3,0.020875,0.000000,0.032022,0.000000,0.003579,0.000000,0.122265,0.011925,0.033471,0.035630,...,0.108506,0.041693,0.000000,0.058217,0.469717,0.000000,0.032708,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
5,0.037441,0.000000,0.000000,0.048161,0.000000,0.052105,0.000000,0.000000,0.021455,0.039282,...,0.000000,0.012961,0.080638,0.052330,0.115120,0.430941,0.040885,0.049651,0.000000,NaN
6,0.020160,0.000000,0.000000,0.025312,0.000000,0.037465,0.000000,0.003724,0.006468,0.008647,...,0.088871,0.004220,0.654959,0.025837,0.073808,0.000000,0.003173,0.039150,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
8,0.026145,0.015936,0.014582,0.024158,0.025617,0.026832,0.025822,0.000000,0.024042,0.024138,...,0.018127,0.000000,0.025781,0.024352,0.014817,0.028892,0.000000,0.023155,0.657604,NaN
9,0.130833,0.049025,0.068495,0.017955,0.121766,0.107174,0.078073,0.000000,0.056841,0.027653,...,0.066991,0.000000,0.110874,0.028038,0.048262,0.000000,0.000000,0.031058,0.000000,0.056962